name: datingapp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.14
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  like_button: ^2.0.5
  animate_do: ^3.3.4
  dotted_border: ^2.1.0
  glass: ^2.0.0+2
  fluttertoast: ^8.2.8
  animated_segmented_tab_control: ^2.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.3
  awesome_notifications: ^0.10.0
  flutter_slidable: ^3.1.1
  http: ^1.2.2
  loading_animation_widget: ^1.3.0
  image_picker: ^1.1.2

  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  firebase_core: ^3.8.1
  logger: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

 
 
 
 
 
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0


flutter:

 
 
 
  uses-material-design: true

 
  assets:
    - images/
    - assets/
 
 

 
 

 
 
 
 
 
  fonts:

    - family: Manrope
      fonts:
        - asset: fonts/manrope-bold.otf
        - asset: fonts/manrope-extrabold.otf
        - asset: fonts/manrope-light.otf
        - asset: fonts/manrope-medium.otf 
        - asset: fonts/manrope-regular.otf 
        - asset: fonts/manrope-semibold.otf 
        - asset: fonts/manrope-thin.otf 

 
 
