import 'dart:io';

import 'package:flutter/material.dart';
import 'package:get/get.dart';

RxInt tabindex = 0.obs;
RxInt datingindex = 0.obs;
RxBool buttonloading = false.obs;
RxBool dataloading = false.obs;
final List<String> imagePaths = [
  "images/d1.png",
  "images/d1.png",
  "images/d1.png",
];

List genderlist = ["Male", "Female", "Both "];
List educationlist = ["Master’s", "Bachelor's", "Prefer not to say "];
final TextEditingController agecontroller = TextEditingController();
final TextEditingController aboutcontroller = TextEditingController();
final TextEditingController heightcontroller = TextEditingController();
final TextEditingController weightcontroller = TextEditingController();
final TextEditingController namecontroller = TextEditingController();
final TextEditingController preferednamecontroller = TextEditingController();
final TextEditingController religioncontroller = TextEditingController();
final TextEditingController castcontroller = TextEditingController();
final TextEditingController languagecontroller = TextEditingController();
RxString? selectedRegion = RxString("");
RxString? selectedSubRegion = RxString("");
RxString? selectedsex = RxString("");
RxString? maritialstatusselected = RxString("");
RxString? intrestselected = RxString("");
RxString? drinkinghabit = RxString("");
RxString? smokinghabit = RxString("");
RxList datingprofilelist = [].obs;
RxMap myprofiledata = {}.obs;
RxMap intrestedlist = {}.obs;
RxMap personalprofilelist = {}.obs;
RxMap personalworklist = {}.obs;
RxString selectedplaceinintrest = ''.obs;
final List<String> drinking = ["Regular", "Ocassionally", "Never"];
final List<String> smoking = ["Regular", "Ocassionally", "Never"];

// List<String> districtsInIndia = [
//   // A
//   "Agar Malwa", "Agra", "Ahmedabad", "Ahmednagar", "Aizawl", "Ajmer", "Akola",
//   "Alappuzha", "Aligarh", "Alipurduar", "Alirajpur", "Allahabad", "Almora",
//   "Alwar", "Ambala", "Ambedkar Nagar", "Amethi", "Amravati", "Amreli",
//   "Amritsar", "Amroha", "Anand", "Anantapur", "Anantnag", "Angul", "Anjaw",
//   "Anuppur", "Araria", "Ariyalur", "Arwal", "Ashoknagar", "Auraiya",
//   "Aurangabad", "Azamgarh",

//   // B
//   "Bagalkot", "Bageshwar", "Baghpat", "Bahraich", "Baksa", "Balaghat",
//   "Balangir", "Balasore", "Ballia", "Balod", "Baloda Bazar", "Balrampur",
//   "Banaskantha", "Banda", "Bandipora", "Bangalore Rural", "Bangalore Urban",
//   "Banka", "Bankura", "Banswara", "Barabanki", "Baramulla", "Baran",
//   "Bareilly", "Bargarh", "Barmer", "Barnala", "Barpeta", "Barwani", "Bastar",
//   "Basti", "Bathinda", "Beed", "Begusarai", "Belagavi", "Bellary", "Betul",
//   "Bhadradri Kothagudem", "Bhagalpur", "Bhandara", "Bharatpur", "Bharuch",
//   "Bhavnagar", "Bhilwara", "Bhind", "Bhiwani", "Bhojpur", "Bhopal", "Bidar",
//   "Bijapur", "Bijnor", "Bikaner", "Bilaspur", "Birbhum", "Bishnupur",
//   "Bokaro", "Bongaigaon", "Botad", "Boudh", "Budaun", "Budgam",
//   "Bulandshahr", "Buldhana", "Bundi", "Burhanpur", "Buxar",

//   // C
//   "Cachar", "Central Delhi", "Chamarajanagar", "Chamba", "Chamoli",
//   "Champawat", "Champhai", "Chandauli", "Chandel", "Chandigarh",
//   "Chandrapur", "Changlang", "Charaideo", "Charkhi Dadri", "Chatra",
//   "Chengalpattu", "Chennai", "Chhatarpur", "Chhindwara", "Chhota Udaipur",
//   "Chikkaballapur", "Chikkamagaluru", "Chirang", "Chitradurga", "Chitrakoot",
//   "Chittoor", "Chittorgarh", "Churachandpur", "Churu", "Coimbatore",
//   "Cooch Behar", "Cuddalore", "Cuttack",

//   // D
//   "Dadra and Nagar Haveli", "Dahod", "Dakshin Dinajpur", "Dakshina Kannada",
//   "Daman", "Damoh", "Dang", "Dantewada", "Darbhanga", "Darjeeling",
//   "Darrang", "Datia", "Dausa", "Davanagere", "Debagarh", "Dehradun",
//   "Deoghar", "Deoria", "Devbhumi Dwarka", "Dewas", "Dhalai", "Dhamtari",
//   "Dhanbad", "Dhar", "Dharmapuri", "Dharwad", "Dhemaji", "Dhenkanal",
//   "Dholpur", "Dhubri", "Dhule", "Dibang Valley", "Dibrugarh", "Dima Hasao",
//   "Dimapur", "Dindigul", "Dindori", "Diu", "Doda", "Dumka", "Dungarpur",
//   "Durg",

//   // E
//   "East Champaran", "East Delhi", "East Garo Hills", "East Godavari",
//   "East Jaintia Hills", "East Kameng", "East Khasi Hills", "East Siang",
//   "East Sikkim", "East Singhbhum", "Ernakulam", "Erode",

//   // F
//   "Faridabad", "Faridkot", "Farrukhabad", "Fatehabad", "Fatehgarh Sahib",
//   "Fatehpur", "Fazilka", "Ferozepur", "Firozabad",

//   // G
//   "Gadag", "Gadchiroli", "Gajapati", "Ganderbal", "Gandhinagar", "Ganganagar",
//   "Ganjam", "Garhwa", "Gariaband", "Gautam Buddha Nagar", "Gaya",
//   "Ghaziabad", "Ghazipur", "Gir Somnath", "Giridih", "Goalpara", "Godda",
//   "Golaghat", "Gonda", "Gondia", "Gopalganj", "Gorakhpur", "Gumla",
//   "Guna", "Guntur", "Gurdaspur", "Gurugram", "Gwalior",

//   "Hamirpur", "Hanumangarh", "Hapur", "Harda", "Hardoi", "Haridwar", "Hassan",
//   "Haveri", "Hazaribagh", "Hingoli", "Hisar", "Hnahthial", "Hooghly",
//   "Hoshangabad",
//   "Hoshiarpur", "Howrah",

//   // I
//   "Idukki", "Imphal East", "Imphal West", "Indore",

//   // J
//   "Jabalpur", "Jagatsinghpur", "Jagtial", "Jaipur", "Jaisalmer", "Jajpur",
//   "Jalandhar", "Jalaun", "Jalgaon", "Jalna", "Jalore", "Jalpaiguri", "Jammu",
//   "Jamnagar", "Jamtara", "Jamui", "Janjgir-Champa", "Jashpur", "Jaunpur",
//   "Jehanabad", "Jhabua", "Jhajjar", "Jhalawar", "Jhansi", "Jharsuguda",
//   "Jhunjhunu", "Jind", "Jodhpur", "Jorhat", "Junagadh",

//   // K
//   "Kabirdham", "Kachchh", "Kadapa", "Kaimur", "Kaithal", "Kakinada",
//   "Kalaburagi", "Kalimpong", "Kallakurichi", "Kamareddy", "Kamjong",
//   "Kamrup", "Kamrup Metropolitan", "Kanchipuram", "Kandhamal", "Kangpokpi",
//   "Kangra", "Kanker", "Kannauj", "Kannur", "Kanpur Dehat", "Kanpur Nagar",
//   "Kanshiram Nagar", "Kanyakumari", "Kapurthala", "Karaikal", "Karauli",
//   "Kargil", "Karimganj", "Karimnagar", "Karnal", "Karur", "Kasaragod",
//   "Kathua", "Katihar", "Katni", "Kaushambi", "Kendrapara", "Kendujhar",
//   "Khagaria", "Khammam", "Khandwa", "Khargone", "Kheda", "Kheri",
//   "Khordha", "Khowai", "Kinnaur", "Kishanganj", "Kishtwar", "Kodagu",
//   "Koderma", "Kohima", "Kolar", "Kolhapur", "Kolkata", "Kollam", "Kondagaon",
//   "Koppal", "Koraput", "Korba", "Koriya", "Kosgi", "Kota", "Kottayam",
//   "Kozhikode", "Krishna", "Krishnagiri", "Kulgam", "Kullu", "Kupwara",
//   "Kurnool", "Kurukshetra", "Kurung Kumey", "Kushinagar", "Kutch", "Kuvvada",

//   // L
//   "Lahaul and Spiti", "Lakhimpur", "Lakhimpur Kheri", "Lakhisarai",
//   "Lakshadweep", "Lalitpur", "Latehar", "Latur", "Lawngtlai", "Leh",
//   "Lohardaga", "Lohit", "Longding", "Lower Dibang Valley",
//   "Lower Siang", "Lower Subansiri", "Lucknow", "Ludhiana",

//   // M
//   "Machilipatnam", "Madhepura", "Madhubani", "Madurai", "Mahabubabad",
//   "Mahabubnagar", "Maharajganj", "Mahasamund", "Mahe", "Mahendragarh",
//   "Mahisagar", "Mahoba", "Mainpuri", "Malappuram", "Malda", "Malkangiri",
//   "Mamit", "Mancherial", "Mandi", "Mandla", "Mandsaur", "Mandya", "Mansa",
//   "Mathura", "Mau", "Mayiladuthurai", "Mayurbhanj", "Medak", "Medchal",
//   "Meerut", "Mehsana", "Mirzapur", "Moga", "Mohali", "Mokokchung", "Mon",
//   "Moradabad", "Morbi", "Morena", "Mumbai City", "Mumbai Suburban",
//   "Mungeli", "Munger", "Murshidabad", "Muzaffarnagar", "Muzaffarpur",
//   "Mysuru",

//   "Nagapattinam", "Nagaur", "Nagpur", "Nainital", "Nalanda", "Nalbari",
//   "Nalgonda", "Namakkal", "Nanded", "Nandurbar", "Narayanpet", "Narmada",
//   "Narsinghpur", "Nashik", "Navsari", "Nayagarh", "Neemuch", "Nellore",
//   "New Delhi", "Nirmal", "Nizamabad", "Noney", "North 24 Parganas",
//   "North Delhi", "North East Delhi", "North Goa", "North Garo Hills",
//   "North Sikkim", "North Tripura", "North West Delhi", "Nuapada",

//   // O
//   "Osmanabad",

//   // P
//   "Pakur", "Palakkad", "Palamu", "Pali", "Palwal", "Panchkula",
//   "Panchmahal", "Panipat", "Panna", "Papum Pare", "Parbhani",
//   "Paschim Bardhaman",
//   "Paschim Medinipur", "Patan", "Pathanamthitta", "Pathankot", "Patiala",
//   "Patna", "Pauri Garhwal", "Perambalur", "Phek", "Pilibhit", "Pithoragarh",
//   "Pondicherry", "Poonch", "Porbandar", "Prakasam", "Pratapgarh",
//   "Prayagraj", "Pulwama", "Pune", "Puri", "Purnia",

//   // Q
//   "Quilon",

//   // R
//   "Raebareli", "Raichur", "Raigad", "Raigarh", "Raipur", "Raisen",
//   "Rajanna Sircilla", "Rajgarh", "Rajkot", "Rajnandgaon", "Rajouri",
//   "Rajsamand", "Ramgarh", "Ramanagara", "Ramanathapuram", "Ramban",
//   "Rampur", "Ranchi", "Rangareddy", "Ratlam", "Ratnagiri", "Rayagada",
//   "Reasi", "Rewa", "Rewari", "Ri-Bhoi", "Rohtak", "Rohtas", "Rudraprayag",
//   "Rupnagar",

//   // S
//   "Sabarkantha", "Sagar", "Saharanpur", "Saharsa", "Sahibganj", "Saiha",
//   "Salem", "Samastipur", "Samba", "Sambalpur", "Sambhal", "Sangareddy",
//   "Sangli", "Sangrur", "Sant Kabir Nagar", "Sant Ravidas Nagar",
//   "Saran", "Satara", "Satna", "Sawai Madhopur", "Sehore", "Senapati",
//   "Seoni", "Seraikela-Kharsawan", "Serchhip", "Shahdol", "Shahjahanpur",
//   "Shajapur", "Shamli", "Sheikhpura", "Sheohar", "Sheopur", "Shimla",
//   "Shimoga", "Shivamogga", "Shivpuri", "Shopian", "Shravasti", "Siddharthnagar",
//   "Siddipet", "Sidhi", "Sikar", "Simdega", "Sindhudurg", "Singrauli",
//   "Sirmaur", "Sirohi", "Sirsa", "Sitamarhi", "Sitapur", "Sivaganga",
//   "Siwan", "Solan", "Solapur", "Sonbhadra", "Sonipat", "South 24 Parganas",
//   "South Delhi", "South East Delhi", "South Goa", "South Garo Hills",
//   "South Salmara-Mankachar", "South Sikkim", "South Tripura",
//   "South West Delhi", "Sri Ganganagar", "Sri Muktsar Sahib",
//   "Srikakulam", "Srinagar", "Subarnapur", "Sukma", "Sultanpur", "Sundargarh",
//   "Supaul", "Surat", "Suratgarh", "Surendranagar", "Surguja",

//   "Tamenglong", "Tapi", "Tarn Taran", "Tawang", "Tehri Garhwal", "Thane",
//   "Thanjavur", "Theni", "Thiruvallur", "Thiruvananthapuram", "Thiruvarur",
//   "Thoothukudi", "Thoubal", "Thrissur", "Tikamgarh", "Tinsukia", "Tirap",
//   "Tiruchirappalli", "Tirunelveli", "Tirupati", "Tirupathur", "Tiruppur",
//   "Tiruvannamalai", "Tonk", "Tuensang", "Tumakuru", "Tutcorn",

//   // U
//   "Udalguri", "Udham Singh Nagar", "Udhampur", "Udupi", "Ujjain",
//   "Ukhrul", "Umaria", "Una", "Unakoti", "Unnao", "Upper Dibang Valley",
//   "Upper Siang", "Upper Subansiri", "Uttar Bastar Kanker", "Uttar Dinajpur",
//   "Uttarkashi", "Udupi",

//   // V
//   "Vadodara", "Vaishali", "Valsad", "Varanasi", "Vellore", "Vidisha",
//   "Vijayapura", "Vikarabad", "Viluppuram", "Virudhunagar", "Visakhapatnam",
//   "Vizianagaram", "Vyara",

//   // W
//   "Wai", "Warangal", "Wardha", "Washim", "Wayanad", "West Champaran",
//   "West Delhi", "West Garo Hills", "West Godavari", "West Jaintia Hills",
//   "West Kameng", "West Karbi Anglong", "West Khasi Hills", "West Siang",
//   "West Sikkim", "West Singhbhum", "West Tripura", "Wokha",

//   // Y
//   "Yadgir", "Yamunanagar", "Yanam", "Yavatmal",

//   // Z
//   "Zunheboto"
// ];

// List<String> placesInUK = [
//   // Cities
//   "Aberdeen",
//   "Armagh",
//   "Bangor",
//   "Bath",
//   "Belfast",
//   "Birmingham",
//   "Bradford",
//   "Brighton and Hove",
//   "Bristol",
//   "Cambridge",
//   "Canterbury",
//   "Cardiff",
//   "Carlisle",
//   "Chelmsford",
//   "Chester",
//   "Chichester",
//   "Colchester",
//   "Coventry",
//   "Derby",
//   "Derry",
//   "Dundee",
//   "Dunfermline",
//   "Durham",
//   "Edinburgh",
//   "Ely",
//   "Exeter",
//   "Glasgow",
//   "Gloucester",
//   "Hereford",
//   "Inverness",
//   "Kingston upon Hull",
//   "Lancaster",
//   "Leeds",
//   "Leicester",
//   "Lichfield",
//   "Lincoln",
//   "Lisburn",
//   "Liverpool",
//   "London",
//   "Londonderry",
//   "Manchester",
//   "Milton Keynes",
//   "Newcastle upon Tyne",
//   "Newport",
//   "Newry",
//   "Norwich",
//   "Nottingham",
//   "Oxford",
//   "Perth",
//   "Peterborough",
//   "Plymouth",
//   "Portsmouth",
//   "Preston",
//   "Ripon",
//   "Salford",
//   "Salisbury",
//   "Sheffield",
//   "Southampton",
//   "St Albans",
//   "St Asaph",
//   "St Davids",
//   "Stirling",
//   "Stoke-on-Trent",
//   "Sunderland",
//   "Swansea",
//   "Truro",
//   "Wakefield",
//   "Wells",
//   "Westminster",
//   "Winchester",
//   "Wolverhampton",
//   "Worcester",
//   "Wrexham",
//   "York",

//   // Counties
//   "Aberdeenshire",
//   "Anglesey",
//   "Angus",
//   "Argyllshire",
//   "Ayrshire",
//   "Banffshire",
//   "Bedfordshire",
//   "Berwickshire",
//   "Brecknockshire",
//   "Buckinghamshire",
//   "Buteshire",
//   "Caernarfonshire",
//   "Caithness",
//   "Cambridgeshire",
//   "Cardiganshire",
//   "Carmarthenshire",
//   "Cheshire",
//   "Clackmannanshire",
//   "Clwyd",
//   "Cornwall",
//   "Cromartyshire",
//   "Cumberland",
//   "Denbighshire",
//   "Derbyshire",
//   "Devon",
//   "Dorset",
//   "Dumfriesshire",
//   "Dunbartonshire",
//   "Durham",
//   "Dyfed",
//   "East Lothian",
//   "East Riding of Yorkshire",
//   "East Sussex",
//   "Essex",
//   "Fife",
//   "Flintshire",
//   "Glamorgan",
//   "Gloucestershire",
//   "Greater London",
//   "Greater Manchester",
//   "Gwent",
//   "Gwynedd",
//   "Hampshire",
//   "Herefordshire",
//   "Hertfordshire",
//   "Huntingdonshire",
//   "Inverness-shire",
//   "Isle of Wight",
//   "Kent",
//   "Kincardineshire",
//   "Kinross-shire",
//   "Kirkcudbrightshire",
//   "Lanarkshire",
//   "Lancashire",
//   "Leicestershire",
//   "Lincolnshire",
//   "Merseyside",
//   "Midlothian",
//   "Monmouthshire",
//   "Montgomeryshire",
//   "Moray",
//   "Nairnshire",
//   "Norfolk",
//   "North Yorkshire",
//   "Northamptonshire",
//   "Northumberland",
//   "Nottinghamshire",
//   "Orkney",
//   "Oxfordshire",
//   "Peeblesshire",
//   "Pembrokeshire",
//   "Perthshire",
//   "Powys",
//   "Renfrewshire",
//   "Ross-shire",
//   "Roxburghshire",
//   "Selkirkshire",
//   "Shetland",
//   "Shropshire",
//   "Somerset",
//   "South Yorkshire",
//   "Staffordshire",
//   "Stirlingshire",
//   "Suffolk",
//   "Surrey",
//   "Sutherland",
//   "Tyne and Wear",
//   "Warwickshire",
//   "West Lothian",
//   "West Midlands",
//   "West Sussex",
//   "West Yorkshire",
//   "Wigtownshire",
//   "Wiltshire",
//   "Worcestershire",
//   "Wrexham",
//   "Yorkshire",
// ];

List<String> placesInUKandIndia = [
  "Abohar",
  "Adilabad",
  "Agra",
  "Ahmedabad",
  "Ahmednagar",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Alappuzha",
  "Aligarh",
  "Alirajpur",
  "Allahabad",
  "Almora",
  "Alwar",
  "Ambala",
  "Ambedkar Nagar",
  "Amethi",
  "Amravati",
  "Amritsar",
  "Anakapalli",
  "Anand",
  "Anantapur",
  "Anantnag",
  "Andaman and Nicobar",
  "Angul",
  "Anjaw",
  "Anuppur",
  "Araria",
  "Aravalli",
  "Ariyalur",
  "Arwal",
  "Ashoknagar",
  "Auraiya",
  "Aurangabad",
  "Azamgarh",
  "Bageshwar",
  "Baghpat",
  "Bahraich",
  "Baksa",
  "Balaghat",
  "Balangir",
  "Balasore",
  "Ballia",
  "Balrampur",
  "Banaskantha",
  "Banda",
  "Bandipora",
  "Bangalore",
  "Banka",
  "Bankura",
  "Banswara",
  "Barabanki",
  "Baramulla",
  "Baran",
  "Bareilly",
  "Bargarh",
  "Barmer",
  "Barnala",
  "Barpeta",
  "Barwani",
  "Bathinda",
  "Beed",
  "Begusarai",
  "Belagavi",
  "Bellary",
  "Betul",
  "Bhadrak",
  "Bhagalpur",
  "Bhandara",
  "Bharatpur",
  "Bharuch",
  "Bhavnagar",
  "Bhilwara",
  "Bhind",
  "Bhiwani",
  "Bhopal",
  "Bidar",
  "Bijapur",
  "Bijnor",
  "Bikaner",
  "Bilaspur",
  "Birbhum",
  "Bishnupur",
  "Bokaro",
  "Bongaigaon",
  "Boudh",
  "Bulandshahr",
  "Bundi",
  "Burhanpur",
  "Buxar",
  "Caerphilly",
  "Cambridge",
  "Camden",
  "Cardiff",
  "Carlisle",
  "Chelmsford",
  "Cheltenham",
  "Chennai",
  "Chhatarpur",
  "Chhindwara",
  "Chikkamagaluru",
  "Chirang",
  "Chitrakoot",
  "Chittoor",
  "Churu",
  "Coimbatore",
  "Cuttack",
  "Darbhanga",
  "Darjeeling",
  "Datia",
  "Dausa",
  "Davanagere",
  "Dehradun",
  "Delhi",
  "Dewas",
  "Dhamtari",
  "Dhanbad",
  "Dhar",
  "Dharwad",
  "Dhemaji",
  "Dhenkanal",
  "Dholpur",
  "Dhubri",
  "Dhule",
  "Dimapur",
  "Dindigul",
  "Dindori",
  "Dungarpur",
  "Durg",
  "Durgapur",
  "East Cambridgeshire",
  "East Cheshire",
  "East Dunbartonshire",
  "East Hampshire",
  "East Hertfordshire",
  "East Lothian",
  "East Midlands",
  "East Renfrewshire",
  "East Riding of Yorkshire",
  "East Staffordshire",
  "East Sussex",
  "East Ayrshire",
  "East Belfast",
  "East Devon",
  "East Dunbartonshire",
  "East Fife",
  "East Kilbride",
  "East Lothian",
  "East Midlands",
  "East Norfolk",
  "East Renfrewshire",
  "East Renfrewshire",
  "East Riding of Yorkshire",
  "East Staffordshire",
  "East Sussex",
  "Ealing",
  "Edinburgh",
  "Epsom and Ewell",
  "Exeter",
  "Falkirk",
  "Fermanagh and Omagh",
  "Fife",
  "Flintshire",
  "Gainsborough",
  "Galway",
  "Gandhinagar",
  "Gaya",
  "Gwalior",
  "Gurgaon",
  "Gulbarga",
  "Gumla",
  "Gurugram",
  "Haora",
  "Haldwani",
  "Haryana",
  "Haverhill",
  "Hazaribagh",
  "Hingoli",
  "Himachal Pradesh",
  "Hindustan",
  "Hooghly",
  "Hyderabad",
  "Hindon",
  "Hoshangabad",
  "Hoshiarpur",
  "Howrah",
  "Hugli",
  "Idukki",
  "Indore",
  "Indri",
  "Irungattukottai",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jammu",
  "Jamshedpur",
  "Jamnagar",
  "Janjgir-Champa",
  "Jashpur",
  "Jind",
  "Jodhpur",
  "Jorhat",
  "Junagadh",
  "Kaithal",
  "Kakinada",
  "Kalahandi",
  "Kamalapuram",
  "Kanchipuram",
  "Kandhamal",
  "Kanpur",
  "Kanyakumari",
  "Karbi Anglong",
  "Karnal",
  "Kasaragod",
  "Kathua",
  "Kattankulathur",
  "Kawardha",
  "Khagaria",
  "Khammam",
  "Khargone",
  "Khargone",
  "Kochi",
  "Kolkata",
  "Koraput",
  "Kottayam",
  "Kozhikode",
  "Kulgam",
  "Kullu",
  "Kurnool",
  "Kurukshetra",
  "Laos",
  "Ladakh",
  "Lakhimpur Kheri",
  "Lakhisarai",
  "Lalitpur",
  "Ludhiana",
  "Lucknow",
  "Lunglei",
  "Madurai",
  "Maharashtra",
  "Malda",
  "Malappuram",
  "Mandi",
  "Manipal",
  "Mansa",
  "Mathura",
  "Meerut",
  "Mewat",
  "Mirzapur",
  "Moga",
  "Mokokchung",
  "Moradabad",
  "Mumbai",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Nagaland",
  "Nagapattinam",
  "Nagaur",
  "Nagpur",
  "Nainital",
  "Nalanda",
  "Nalbari",
  "Nalgonda",
  "Namakkal",
  "Nanded",
  "Nandurbar",
  "Narayanpet",
  "Narmada",
  "Narsinghpur",
  "Nashik",
  "Navsari",
  "Nayagarh",
  "Neemuch",
  "Nellore",
  "New Delhi",
  "Nirmal",
  "Nizamabad",
  "Noney",
  "North 24 Parganas",
  "North Delhi",
  "North East Delhi",
  "North Goa",
  "North Garo Hills",
  "North Sikkim",
  "North Tripura",
  "North West Delhi",
  "Nuapada",
  "Odisha",
  "Osmanabad",
  "Panchkula",
  "Panchmahal",
  "Panipat",
  "Panna",
  "Papupara",
  "Parbhani",
  "Paschim Medinipur",
  "Patan",
  "Pathanamthitta",
  "Patan",
  "Patiala",
  "Patna",
  "Perambalur",
  "Phek",
  "Pilibhit",
  "Pithoragarh",
  "Pondicherry",
  "Poonch",
  "Porbandar",
  "Prakasam",
  "Pratapgarh",
  "Prayagraj",
  "Pulwama",
  "Pune",
  "Purnia",
  "Puri",
  "Puducherry",
  "Raebareli",
  "Raichur",
  "Raigad",
  "Raigarh",
  "Raipur",
  "Raisen",
  "Rajanna Sircilla",
  "Rajgarh",
  "Rajkot",
  "Rajnandgaon",
  "Rajouri",
  "Rajsamand",
  "Ramgarh",
  "Ramanagara",
  "Ramanathapuram",
  "Ramban",
  "Rampur",
  "Ranchi",
  "Rangareddy",
  "Ratlam",
  "Ratnagiri",
  "Rayagada",
  "Reasi",
  "Rewa",
  "Rewari",
  "Ri-Bhoi",
  "Rohtak",
  "Rohtas",
  "Rudraprayag",
  "Rupnagar",
  "Sabarkantha",
  "Sadar Bazar",
  "Sagar",
  "Saharanpur",
  "Saharsa",
  "Sahibganj",
  "Saiha",
  "Salem",
  "Samastipur",
  "Samba",
  "Sambalpur",
  "Sambhal",
  "Sangli",
  "Sangrur",
  "Sanjay Nagar",
  "Sant Kabir Nagar",
  "Sant Ravidas Nagar",
  "Saran",
  "Satara",
  "Satna",
  "Sawai Madhopur",
  "Sehore",
  "Seoni",
  "Seraikela-Kharsawan",
  "Serchhip",
  "Shahdol",
  "Shahjahanpur",
  "Shajapur",
  "Shamli",
  "Sheikhpura",
  "Sheohar",
  "Sheopur",
  "Shimla",
  "Shimoga",
  "Shivamogga",
  "Shivpuri",
  "Shopian",
  "Shravasti",
  "Siddharthnagar",
  "Siddipet",
  "Sidhi",
  "Sikar",
  "Simdega",
  "Sindhudurg",
  "Singrauli",
  "Sirmaur",
  "Sirohi",
  "Sirsa",
  "Sitamarhi",
  "Sitapur",
  "Sivaganga",
  "Siwan",
  "Solan",
  "Solapur",
  "Sonbhadra",
  "Sonipat",
  "South 24 Parganas",
  "South Delhi",
  "South East Delhi",
  "South Goa",
  "South Garo Hills",
  "South Sikkim",
  "South Tripura",
  "South West Delhi",
  "Sri Ganganagar",
  "Sri Muktsar Sahib",
  "Srikakulam",
  "Srinagar",
  "Subarnapur",
  "Sukma",
  "Sultanpur",
  "Sundargarh",
  "Supaul",
  "Surat",
  "Suratgarh",
  "Surendranagar",
  "Surguja",
  "Tapi",
  "Tarn Taran",
  "Tawang",
  "Tehri Garhwal",
  "Thane",
  "Thanjavur",
  "Theni",
  "Thiruvallur",
  "Thiruvananthapuram",
  "Thiruvarur",
  "Thoothukudi",
  "Thoubal",
  "Thrissur",
  "Tikamgarh",
  "Tinsukia",
  "Tirap",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Tirupathur",
  "Tiruppur",
  "Tiruvannamalai",
  "Tonk",
  "Tuensang",
  "Tumakuru",
  "Tutcorn",
  "Udalguri",
  "Udham Singh Nagar",
  "Udhampur",
  "Udupi",
  "Ujjain",
  "Ukhrul",
  "Umaria",
  "Una",
  "Unakoti",
  "Unnao",
  "Upper Dibang Valley",
  "Upper Siang",
  "Upper Subansiri",
  "Uttar Bastar Kanker",
  "Uttar Dinajpur",
  "Uttarkashi",
  "Udupi",
  "Vadodara",
  "Vaishali",
  "Valsad",
  "Varanasi",
  "Vellore",
  "Vidisha",
  "Vijayapura",
  "Vikarabad",
  "Viluppuram",
  "Virudhunagar",
  "Visakhapatnam",
  "Vizianagaram",
  "Vyara",
  "Wai",
  "Warangal",
  "Wardha",
  "Washim",
  "Wayanad",
  "West Champaran",
  "West Delhi",
  "West Garo Hills",
  "West Godavari",
  "West Jaintia Hills",
  "West Kameng",
  "West Karbi Anglong",
  "West Khasi Hills",
  "West Siang",
  "West Sikkim",
  "West Singhbhum",
  "West Tripura",
  "Wigan",
  "Wokha",
  "Yadgir",
  "Yamunanagar",
  "Yanam",
  "Yavatmal",
  "Zunheboto"
];

final List<String> dpimage = [
  "dpimage.png",
];
final TextEditingController jobrolecontroller = TextEditingController();
RxInt educationindex = 0.obs;
RxString educationselected = "Master’s".obs;

final TextEditingController collegenamecontroller = TextEditingController();
String? imageName;
File? selectedImage;
final List<String> imageNames = [];
final List<File> images = [];
final List<String> gender = ["Male", "Femele", "Others"];
final List<String> maritialstatus = ["Single", "Commited", "Others"];
final List<String> intrest = ["Intrest1", "Intrest2", "Intrest3"];
final List<String> region = [
  "UK",
  "INDIA",
];
List<String> commonInterests = [
  "Sports and Fitness",
  "Music",
  "Travel",
  "Cooking and Baking",
  "Movies and TV Shows",
  "Books and Literature",
  "Gaming",
  "Photography",
  "Pets",
  "Fashion",
  "Volunteering",
  "Sustainability",
  "Technology",
  "Comedy",
  "Astrology",
];
